# Generated by Django 3.1.3 on 2020-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('prenom', models.CharField(default='', max_length=255)),
                ('Email', models.EmailField(default='', max_length=255)),
            ],
        ),
    ]
